project_id = "wsiorhtiovwcajiarydw"

# Public functions (webhooks, external integrations) - no JWT required
[functions.security-monitor]
verify_jwt = false

[functions.camerpulse-twitter]
verify_jwt = false

[functions.civic-alert-bot]
verify_jwt = false

[functions.government-minister-scraper]
verify_jwt = false

[functions.government-website-scraper]
verify_jwt = false

[functions.minat-party-scraper]
verify_jwt = false

[functions.assembly-scraper]
verify_jwt = false

[functions.mp-data-importer]
verify_jwt = false

[functions.minister-data-importer]
verify_jwt = false

[functions.data-import-scheduler]
verify_jwt = false

[functions.export-sponsor-data]
verify_jwt = false

# Internal processing functions - require authentication
[functions.camerpulse-intelligence-core]
verify_jwt = true

[functions.camerpulse-social-apis]
verify_jwt = true

[functions.camerpulse-processor]
verify_jwt = true

[functions.civic-auto-sync-engine]
verify_jwt = true

[functions.civic-import-core-sync]
verify_jwt = true

[functions.civic-integrity-monitor]
verify_jwt = true

[functions.civic-intelligence-missions]
verify_jwt = true

[functions.civic-media-watch]
verify_jwt = true

[functions.civic-strategist-core]
verify_jwt = true

[functions.custom-integrator-builder]
verify_jwt = true

[functions.daily-report-generator]
verify_jwt = true

[functions.face-verification-engine]
verify_jwt = true

[functions.generate-poll-suggestions]
verify_jwt = true

[functions.gov-change-tracker]
verify_jwt = true

[functions.human-simulation-engine]
verify_jwt = true

[functions.legal-intelligence-core]
verify_jwt = true

[functions.local-sentiment-mapper]
verify_jwt = true

[functions.multimodal-emotion-processor]
verify_jwt = true

[functions.natural-language-plugin-builder]
verify_jwt = true

[functions.pan-africa-mesh-manager]
verify_jwt = true

[functions.plugin-stress-watchdog]
verify_jwt = true

[functions.politica-ai-manager]
verify_jwt = true

[functions.politica-ai-scanner]
verify_jwt = true

[functions.prompt-intelligence-engine]
verify_jwt = true

[functions.signal-intelligence-core]
verify_jwt = true

[functions.system-cache-flush]
verify_jwt = true

[functions.ui-visual-inspector]
verify_jwt = true

# Ashen system functions - require authentication
[functions.ashen-auto-healer]
verify_jwt = true

[functions.ashen-autonomous-monitor]
verify_jwt = true

[functions.ashen-behavior-tester]
verify_jwt = true

[functions.ashen-code-scanner]
verify_jwt = true

[functions.ashen-debug-core]
verify_jwt = true

[functions.ashen-dev-terminal]
verify_jwt = true

[functions.ashen-fix-suggestion-engine]
verify_jwt = true

[functions.ashen-jr-training]
verify_jwt = true

[functions.ashen-learning-engine]
verify_jwt = true

[functions.ashen-monitoring-service]
verify_jwt = true

[functions.ashen-security-engine]
verify_jwt = true

[functions.ashen-snapshot-manager]
verify_jwt = true

[functions.ashen-sync-guard]
verify_jwt = true

[functions.autonomous-refresh-engine]
verify_jwt = true

[functions.ashen-auto-sync-engine]
verify_jwt = true

[functions.test-dummy-module]
verify_jwt = true

# Chat enhancement functions - no JWT required for public access
[functions.support-bot]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-voice]
verify_jwt = false

# Shipping and logistics functions - no JWT required for public tracking
[functions.track-shipment]
verify_jwt = false

[functions.update-tracking]
verify_jwt = false