-- Insert notification flow configurations
INSERT INTO public.notification_flows (event_name, template_name, recipient_type, channels, status, timing_type, metadata) VALUES
('artist_submission', 'artist_submission_received', 'artist', ARRAY['email'], 'active', 'immediate', '{}'),
('artist_approved', 'artist_approved_verified', 'artist', ARRAY['email', 'in_app'], 'active', 'immediate', '{}'),
('artist_rejected', 'artist_profile_rejected', 'artist', ARRAY['email'], 'active', 'immediate', '{}'),
('new_follower', 'artist_new_follower', 'artist', ARRAY['in_app'], 'active', 'real_time', '{}'),
('song_uploaded', 'song_uploaded_confirmation', 'artist', ARRAY['email'], 'active', 'immediate', '{}'),
('song_uploaded_notify_fans', 'notify_fans_new_song', 'fan', ARRAY['email', 'in_app', 'push'], 'active', 'immediate', '{}'),
('stream_milestone', 'stream_milestone_alert', 'artist', ARRAY['in_app'], 'active', 'threshold', '{}'),
('song_added_to_playlist', 'song_added_to_playlist', 'artist', ARRAY['in_app'], 'active', 'real_time', '{}'),
('award_nomination_artist', 'award_nomination_notice', 'artist', ARRAY['email', 'in_app'], 'active', 'immediate', '{}'),
('award_nomination_notify_fans', 'fan_award_nomination_alert', 'fan', ARRAY['email', 'in_app'], 'active', 'immediate', '{}'),
('award_voting_open', 'award_voting_open', 'public', ARRAY['email', 'in_app'], 'active', 'scheduled', '{}'),
('award_voting_close', 'award_voting_closed', 'artist', ARRAY['in_app'], 'active', 'scheduled', '{}'),
('award_winner_announcement', 'artist_award_winner_announcement', 'artist', ARRAY['email', 'in_app'], 'active', 'immediate', '{}'),
('event_published', 'event_published_confirmation', 'artist', ARRAY['email'], 'active', 'immediate', '{}'),
('event_published_notify_fans', 'notify_fans_new_event', 'fan', ARRAY['email', 'in_app'], 'active', 'immediate', '{}'),
('ticket_purchase', 'ticket_purchase_confirmation', 'buyer', ARRAY['email', 'dashboard'], 'active', 'immediate', '{}'),
('event_reminder_24h', 'event_reminder_24h', 'buyer', ARRAY['email', 'push', 'sms'], 'active', 'scheduled', '{}'),
('event_replay_available', 'event_replay_link', 'attendee', ARRAY['email', 'in_app'], 'active', 'post_event', '{}'),
('event_canceled', 'event_cancellation_notice', 'buyer', ARRAY['email'], 'active', 'immediate', '{}'),
('badge_awarded', 'badge_award_notification', 'artist', ARRAY['in_app'], 'active', 'immediate', '{}');

-- Insert corresponding notification templates
INSERT INTO public.notification_templates (template_name, channel, subject_template, body_template, metadata) VALUES
('artist_submission_received', 'email', 'Artist Application Received', 'Thank you for submitting your artist application to CamerPlay. We will review your submission and get back to you within 5-7 business days.', '{}'),
('artist_approved_verified', 'email', 'Welcome to CamerPlay - Application Approved!', 'Congratulations! Your artist application has been approved. You can now access all CamerPlay features.', '{}'),
('artist_profile_rejected', 'email', 'Artist Application Update', 'Thank you for your interest in CamerPlay. Unfortunately, your application needs some changes before approval. Please review our feedback and resubmit.', '{}'),
('artist_new_follower', 'in_app', 'New Follower', 'You have a new follower on CamerPlay!', '{}'),
('song_uploaded_confirmation', 'email', 'Song Upload Successful', 'Your song has been successfully uploaded to CamerPlay and is now live!', '{}'),
('notify_fans_new_song', 'email', 'New Music Alert', 'Your favorite artist has just released new music on CamerPlay!', '{}'),
('stream_milestone_alert', 'in_app', 'Streaming Milestone Reached', 'Congratulations! Your song has reached a new streaming milestone.', '{}'),
('song_added_to_playlist', 'in_app', 'Playlist Addition', 'Your song was added to a playlist!', '{}'),
('award_nomination_notice', 'email', 'Award Nomination', 'Congratulations! You have been nominated for a CamerPlay award.', '{}'),
('fan_award_nomination_alert', 'email', 'Your Artist Nominated', 'Great news! An artist you follow has been nominated for an award.', '{}'),
('award_voting_open', 'email', 'Award Voting Now Open', 'Voting is now open for the CamerPlay Awards. Cast your vote now!', '{}'),
('award_voting_closed', 'in_app', 'Voting Closed', 'Award voting has closed. Results will be announced soon.', '{}'),
('artist_award_winner_announcement', 'email', 'Congratulations - Award Winner!', 'Congratulations! You have won a CamerPlay award!', '{}'),
('event_published_confirmation', 'email', 'Event Published', 'Your event has been successfully published on CamerPlay.', '{}'),
('notify_fans_new_event', 'email', 'New Event Alert', 'Your favorite artist has announced a new event!', '{}'),
('ticket_purchase_confirmation', 'email', 'Ticket Purchase Confirmation', 'Thank you for your ticket purchase. Your tickets are confirmed!', '{}'),
('event_reminder_24h', 'email', 'Event Reminder - 24 Hours', 'Reminder: Your event is happening in 24 hours!', '{}'),
('event_replay_link', 'email', 'Event Replay Available', 'The replay of your recent event is now available.', '{}'),
('event_cancellation_notice', 'email', 'Event Cancellation Notice', 'Unfortunately, the event you purchased tickets for has been cancelled.', '{}'),
('badge_award_notification', 'in_app', 'Badge Earned', 'Congratulations! You have earned a new badge.', '{}');