-- Create a test shipment for demonstration
INSERT INTO shipments (
  tracking_number, 
  sender_name, 
  sender_address, 
  sender_city, 
  sender_state, 
  sender_postal_code, 
  sender_country,
  receiver_name, 
  receiver_address, 
  receiver_city, 
  receiver_state, 
  receiver_postal_code, 
  receiver_country,
  service_level, 
  package_weight, 
  package_dimensions, 
  declared_value, 
  status,
  estimated_delivery_date
) VALUES (
  'CP' || LPAD(FLOOR(RANDOM() * 1000000)::TEXT, 6, '0'),
  'CamerPulse Express',
  '123 Business District',
  'Douala',
  'Littoral',
  '00237',
  'Cameroon',
  'Jean Mballa',
  '456 Residential Avenue',
  'Yaoundé',
  'Centre',
  '00237',
  'Cameroon',
  'express',
  2.5,
  '{"length": 30, "width": 20, "height": 15}',
  75000,
  'in_transit',
  CURRENT_DATE + INTERVAL '2 days'
);