-- Insert senator data from senat.cm
INSERT INTO public.senators (name, position, photo_url, about) VALUES 
('NIAT NJIFENJI Marcel', 'Président du Sénat', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs.jpg', ''),
('Sa Majesté ABOUBAKARY ABDOULAYE', '1er Vice président', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs4.jpg', 'Lamido de REY-BOUBA, membre des Commissions des affaires étrangères, et celle des lois constitutionnelles'),
('H.M. NFOR TABETANDO NDIEB-NSO', 'Vice-président', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs88.jpg', ''),
('Nkili Robert', 'Vice-président', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs68.jpg', 'membre de la commission des affaires économiques ; de la commission des résolutions et des pétitions. Ancien Ministre, membre titulaire du Comité central du RDPC'),
('DIN BELL ARMANDE', 'Vice-président au Bureau du Sénat', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs19.jpg', 'Ex Député à l''Assemblée Nationale, membre de la commission de la défense nationale et de la sécurité ; et la commission de la production et des échanges'),
('Mochiggle Vanigangsen', 'Vice-président', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs91.jpg', ''),
('Fon CHAFAH Issac', 'Secrétaire au Bureau du Sénat; Membre de la Commission des lois constitutionnelles, et de la Commission des Affaires étrangères.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs29.jpg', 'Magistrat hors-échelle, Fon'),
('NGAYAP Pierre Flambeau', 'Secrétaire au Bureau du Sénat, Membre de la commission des Lois Constitutionnelles, des droits de l''homme, des libertés, de la justice, de la législation, du règlement et de l''administration ; et la commission des Affaires Economiques.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs63.jpg', 'Pharmacien'),
('Ngouchinghe Sylvestre', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs66.jpg', ''),
('OBAM ASSAM Samuel', 'Membre de la Commission des Affaires Economiques, de la Planification et de l''Aménagement du Territoire', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs71.jpg', 'Journaliste principal, ancien Directeur du Courrier Présidentiel'),
('Abba Harouna', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs2.jpg', ''),
('HAYATOU AÏCHA Pierrette', 'secrétaire au bureau et membre de la commission des affaires économiques, de la programmation et de l''aménagement du territoire et celle de la défense nationale et de la sécurité.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs32.jpg', ''),
('Begala Mikel N. épse Akono', 'Secrétaire au Bureau du Sénat ; membre de la commission des affaires culturelles, sociales et familiales', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs11.jpg', 'Ex Ministre plénipotentiaire'),
('LEKE BESONGOH AKEMFOR Philip', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs39.jpg', ''),
('ABDOULAYE WOUYACK MARAVA', 'Questeur au Bureau du Sénat, Membre de la Commission des Finances et du Budget, et la Commission des Lois Constitutionnelles', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs3.jpg', ''),
('BISSECK Paulette', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs14.jpg', ''),
('OTTE Andrew MOFA', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs73.jpg', ''),
('TCHUETCHUE MBOKOUOKO Rodrigue', 'Décédé', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs100.jpg', 'Chef supérieur du Groupement Bati-Galim'),
('MAMOUDOU MAZADOU', 'Membre de la Commission de la Production et des Echanges', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs99.jpg', ''),
('BAROUA NYAKEU', 'membre de la commission de l''Education, de la formation professionnelle et de la jeunesse.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs98.jpg', 'Enseignant'),
('ZOUBAÏNATOU SALIHOU épse BASSIROU', 'Membre des commissions des Affaires Etrangères ; et celle de la défense nationale', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs97.jpg', 'Fonctionnaire des greffes, ex député à l''Assemblée nationale'),
('ZE NGUELE René', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs96.jpg', ''),
('ZANG OYONO Calvin', 'Décédé', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs95.jpg', 'Président du groupe parlementaire RDPC de 2018 à 2025, membre de la commission des finances et du budget, et de la commission des Résolutions et Pétitions.'),
('ZAKIATOU épse SALE', 'Membre de la commission de la Production et des Échanges', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs94.jpg', 'Membre du Comité Central du RDPC'),
('Yvonne ASTA', 'Membre de la commission des Affaires Culturelles', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs93.jpg', 'Infirmière'),
('WAIDERE D épse BINGUELA', 'Membre de la commission de la Production et des Échanges', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs92.jpg', ''),
('TIZI TOURMBA MALAYE Yves', 'Président de la Commission de la Production et des Echanges, Membre de la Commission des Résolutions et des Pétitions', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs90.jpg', 'Expert en microfinance et développement local, Coordonnateur départemental adjoint du FSNC dans le Mayo-Louti.'),
('TABI Pierre Emmanuel', 'Secrétaire de la commission de l''éduction, de la formation professionnelle et membre de la commission des Affaires Etrangères', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs89.jpg', ''),
('SOUROUHOUL Emmanuel', 'Membre de la Commission de la Défense nationale et de la sécurité, la commission des Affaires Culturelles', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs87.jpg', ''),
('SOURNAC Henriette', 'Membre de la Commission des Affaires culturelles, Sociales et Familiales ; de la commission de la production et des échanges.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs86.jpg', ''),
('SOUADATOU D épse KALKABA', 'Membre de la commission des affaires culturelles, sociales et familiales.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs85.jpg', 'Diplômée en management du Sport et en gestion des organisations sportives olympiques au Cameroun'),
('SEIDOU MBOMBO NDJOYA', 'Membre de la Commission des finances', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs84.jpg', ''),
('SALI MOHAMAN', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs83.jpg', ''),
('SALAMATOU épse MOUSSA Martine', 'Membre de la commission de la Formation Professionnelle', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs82.jpg', 'Enseignante'),
('ROUGAYATOU ASTA DJOULDE', 'Membre de la commission de l''éducation, de la formation professionnelle et de la jeunesse et celle des Résolutions et pétitions.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs81.jpg', ''),
('PUENE Francoise', 'Membre de la commission des Affaires Culturelles ; Production et des Echanges', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs80.jpg', 'Entrepreneur, Opérateur économique, Infirmière d''Etat'),
('PONGMONI Jean-Marie', 'Vice-président de la commission de la défense nationale et de la sécurité ; membre de la commission des Lois constitutionnelles.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs79.jpg', 'Administrateur pénitencier'),
('POKAM Max', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs78.jpg', ''),
('PAPINATU FONDERSON Lionel', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs77.jpg', ''),
('OUMAROU VAIDANG', 'Membre de la commission des Affaires Culturelles', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs76.jpg', ''),
('OUMAROU MAZADOU', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs75.jpg', ''),
('OUMAROU ISSA', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs74.jpg', ''),
('OKALA BILAÏ Nicole épse AHANDJENA', 'Présidente de la commission des affaires étrangères ; membre de la commission de l''Education, de la formation professionnelle et de la Jeunesse.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs72.jpg', 'Ancien Maire, Membre du Comité central du RDPC'),
('NTUBE Agnès épse NDJOCK', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs70.jpg', ''),
('NKODO Laurent', 'président de la Commission des finances et du budget', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs69.jpg', 'Inspecteur Principal des Impôts Hors Echelle, membre titulaire du Comité Central du Rdpc'),
('NIKAMANE Nathanaël', 'Membre de la commission de l''Éducation', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs67.jpg', 'Enseignant'),
('NGO''OBOMA épse YINDA Yvette Josette Jacqueline', 'Membre de la Commission des Affaires Culturelles', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs65.jpg', 'Entrepreneur; militante RDPC, ancien Conseiller Municipal de Pouma'),
('NGBWA BALA Yvette', 'Membre de la Commission des Affaires Economiques, de la Planification et de l''Aménagement du Territoire', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs64.jpg', ''),
('NGANGOUBE AMINATOU', 'Présidente Adjoint du Groupe Parlementaire RDPC-Ouest ; membre de la commission de la Défense et de la Sécurité Nationale ; de la commission des Affaires Economiques, de la Programmation et de l''Aménagement du Territoire', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs62.jpg', ''),
('NGANDO NGONDE épse SOPPO SOPPO', 'Membre de la commission de la Formation Professionnelle, de l''Education et de la Jeunesse', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs61.jpg', ''),
('NGALLI NGOUA Pierre Henri', 'Membre des commissions des Affaires Etrangères ; et des Affaires Economiques', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs60.jpg', 'Economiste, ancien fonctionnaire de la BAD, Consultant au FMI'),
('NGAFESSON Emmanuel', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs59.jpg', ''),
('NEBA NDOSIRI Bridget NDOYE', 'Membre de la Commission de l''Education, de la Formation professionnelle; la Commission des Résolutions et des Pétitions', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs58.jpg', 'Maître des Conférences'),
('NDANGA NDINGA Badel', 'Nouveau Président du groupe parlementaire RDPC, Vice-président de la commission des affaires économiques et membre de la commission des Lois Constitutionnelles', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs57.jpg', 'Administrateur civil principal hors échelle, ancien Ministre, ancien Député'),
('MUNDI Regina Elisabeth', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs56.jpg', ''),
('MOUSSA SABO', 'Membre de la Commission des finances et du budget ; de la commission des affaires économiques, de la programmation et de l''aménagement du territoire.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs55.jpg', 'Inspecteur de police principal à la retraite, chef traditionnel de 1er degré'),
('MOUEN DIBOUNDJE Ernest', 'Président de la commission des Affaires économiques, de la programmation et de l''aménagement du territoire', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs54.jpg', ''),
('MOSONGO Ernestine AKON NJONG', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs53.jpg', ''),
('MOHAMAN GABDO', 'Membre de la commission de l''éducation, de la formation professionnelle et de la jeunesse et celle des Résolutions et pétitions.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs52.jpg', 'Lamido du Mayo-Banyo'),
('Mireille ADARE GASSAWILLY', 'Décédée', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs51.jpg', ''),
('MENYE ONDO Pierre Francois Xavier', 'Membre de la Commission de la production et des Echanges', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs50.jpg', 'Notaire'),
('MBUFONG Carl Moses FONTONG', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs49.jpg', ''),
('MBITA NVAEBEME Lippert Daniel Raymond', 'Membre de la Commission de la défense et sécurité nationale, et la commission des Affaires Culturelles', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs48.jpg', 'Inspecteur principal des Impôts'),
('MBELA MOKI Charles', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs47.jpg', ''),
('MBA MBA Grégoire', 'Questeur au Bureau du Sénat depuis 2024', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs46.jpg', 'Directeur général de plusieurs sociétés'),
('MANGA ZANG', '', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs45.jpg', ''),
('MAMA Jean Marie', 'Membre de la Commission des Affaires Etrangères, de la commission des Affaires Culturelles, sociales et Familiales.', 'https://senat.cm/wp-content/uploads/2023/09/Portrait-des-Senateurs44.jpg', 'Contrôleur financier, Chef Traditionnel');