-- Make created_by nullable for system templates
ALTER TABLE label_templates ALTER COLUMN created_by DROP NOT NULL;

-- Insert 10 shipping label templates with diverse designs
INSERT INTO label_templates (template_name, template_config, template_type, is_active) VALUES
('Standard Shipping Label', '{"layout": "standard", "fields": [{"id": "sender", "type": "text", "position": {"x": 20, "y": 20}, "size": {"width": 200, "height": 80}}, {"id": "receiver", "type": "text", "position": {"x": 20, "y": 120}, "size": {"width": 200, "height": 80}}, {"id": "tracking", "type": "barcode", "position": {"x": 250, "y": 20}, "size": {"width": 150, "height": 40}}, {"id": "qr_code", "type": "qr_code", "position": {"x": 250, "y": 80}, "size": {"width": 60, "height": 60}}], "colors": {"primary": "#1f2937", "secondary": "#6b7280"}}', 'shipping_label', true),
('Express Delivery Label', '{"layout": "express", "fields": [{"id": "priority_badge", "type": "text", "position": {"x": 10, "y": 10}, "size": {"width": 100, "height": 30}}, {"id": "sender", "type": "text", "position": {"x": 20, "y": 50}, "size": {"width": 180, "height": 70}}, {"id": "receiver", "type": "text", "position": {"x": 20, "y": 130}, "size": {"width": 180, "height": 70}}, {"id": "tracking", "type": "barcode", "position": {"x": 220, "y": 50}, "size": {"width": 120, "height": 35}}], "colors": {"primary": "#dc2626", "secondary": "#fca5a5"}}', 'shipping_label', true),
('International Shipping', '{"layout": "international", "fields": [{"id": "customs_info", "type": "text", "position": {"x": 10, "y": 10}, "size": {"width": 200, "height": 40}}, {"id": "sender", "type": "text", "position": {"x": 20, "y": 60}, "size": {"width": 160, "height": 60}}, {"id": "receiver", "type": "text", "position": {"x": 20, "y": 130}, "size": {"width": 160, "height": 80}}, {"id": "tracking", "type": "barcode", "position": {"x": 200, "y": 60}, "size": {"width": 100, "height": 30}}], "colors": {"primary": "#059669", "secondary": "#34d399"}}', 'shipping_label', true),
('Thermal 4x6 Standard', '{"layout": "thermal_4x6", "thermal_optimized": true, "fields": [{"id": "sender", "type": "text", "position": {"x": 10, "y": 10}, "size": {"width": 180, "height": 60}}, {"id": "receiver", "type": "text", "position": {"x": 10, "y": 80}, "size": {"width": 180, "height": 80}}, {"id": "tracking", "type": "barcode", "position": {"x": 200, "y": 10}, "size": {"width": 150, "height": 40}}], "colors": {"primary": "#000000", "background": "#ffffff"}}', 'thermal_label', true),
('Modern Minimal', '{"layout": "modern_minimal", "fields": [{"id": "logo", "type": "image", "position": {"x": 10, "y": 10}, "size": {"width": 50, "height": 30}}, {"id": "sender", "type": "text", "position": {"x": 70, "y": 10}, "size": {"width": 150, "height": 50}}, {"id": "receiver", "type": "text", "position": {"x": 10, "y": 70}, "size": {"width": 210, "height": 80}}, {"id": "tracking_qr", "type": "qr_code", "position": {"x": 240, "y": 10}, "size": {"width": 80, "height": 80}}], "colors": {"primary": "#3b82f6", "secondary": "#e5e7eb", "accent": "#10b981"}}', 'shipping_label', true),
('Clean Corporate', '{"layout": "corporate", "fields": [{"id": "company_header", "type": "text", "position": {"x": 10, "y": 10}, "size": {"width": 300, "height": 30}}, {"id": "sender_box", "type": "text", "position": {"x": 20, "y": 50}, "size": {"width": 140, "height": 80}}, {"id": "receiver_box", "type": "text", "position": {"x": 170, "y": 50}, "size": {"width": 140, "height": 80}}, {"id": "tracking_section", "type": "barcode", "position": {"x": 20, "y": 140}, "size": {"width": 200, "height": 40}}], "colors": {"primary": "#1f2937", "secondary": "#f3f4f6", "brand": "#6366f1"}}', 'shipping_label', true),
('Fragile Items Label', '{"layout": "fragile", "fields": [{"id": "fragile_warning", "type": "text", "position": {"x": 10, "y": 10}, "size": {"width": 300, "height": 40}}, {"id": "sender", "type": "text", "position": {"x": 170, "y": 55}, "size": {"width": 140, "height": 40}}, {"id": "receiver", "type": "text", "position": {"x": 170, "y": 100}, "size": {"width": 140, "height": 60}}, {"id": "tracking", "type": "barcode", "position": {"x": 10, "y": 125}, "size": {"width": 150, "height": 35}}], "colors": {"primary": "#dc2626", "warning": "#f59e0b", "background": "#fef2f2"}}', 'shipping_label', true),
('Cold Chain Label', '{"layout": "cold_chain", "fields": [{"id": "temperature_warning", "type": "text", "position": {"x": 10, "y": 10}, "size": {"width": 200, "height": 30}}, {"id": "sender", "type": "text", "position": {"x": 10, "y": 50}, "size": {"width": 150, "height": 60}}, {"id": "receiver", "type": "text", "position": {"x": 170, "y": 50}, "size": {"width": 150, "height": 60}}, {"id": "tracking", "type": "barcode", "position": {"x": 10, "y": 120}, "size": {"width": 180, "height": 35}}], "colors": {"primary": "#0ea5e9", "secondary": "#e0f2fe", "warning": "#0891b2"}}', 'shipping_label', true),
('Rural Delivery', '{"layout": "rural", "fields": [{"id": "rural_route", "type": "text", "position": {"x": 10, "y": 10}, "size": {"width": 150, "height": 25}}, {"id": "sender", "type": "text", "position": {"x": 10, "y": 60}, "size": {"width": 150, "height": 70}}, {"id": "receiver", "type": "text", "position": {"x": 170, "y": 60}, "size": {"width": 140, "height": 70}}, {"id": "tracking", "type": "barcode", "position": {"x": 10, "y": 140}, "size": {"width": 180, "height": 30}}], "colors": {"primary": "#059669", "secondary": "#d1fae5"}}', 'shipping_label', true),
('Premium Brand Label', '{"layout": "premium_brand", "fields": [{"id": "brand_header", "type": "text", "position": {"x": 10, "y": 10}, "size": {"width": 300, "height": 35}}, {"id": "sender_premium", "type": "text", "position": {"x": 100, "y": 50}, "size": {"width": 100, "height": 50}}, {"id": "receiver_premium", "type": "text", "position": {"x": 210, "y": 50}, "size": {"width": 100, "height": 50}}, {"id": "gold_tracking", "type": "barcode", "position": {"x": 10, "y": 110}, "size": {"width": 200, "height": 35}}], "colors": {"primary": "#92400e", "secondary": "#fef3c7", "accent": "#d97706"}}', 'shipping_label', true);